# Generated by Django 2.0.2.dev20180120075511 on 2018-01-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foo',
            name='bar',
            field=models.ManyToManyField(blank=True, to='myapp.Foo'),
        ),
    ]
